# This is a dry run build that does not publish the container to github registry
name: Build Docker Container

on:
  push:
    branches-ignore:
     - main
env:
  REGISTRY: ghcr.io
  BASE_IMG_NAME: ${{ github.repository }}
jobs:
  build-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Derive short SHA name
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile \
          --tag ghcr.io/${{ env.BASE_IMG_NAME }}:${{ steps.vars.outputs.sha_short }} \
          --tag ghcr.io/${{ env.BASE_IMG_NAME }}:latest
